version: "3.8" 

services:
  app:
    #image: myimage # Image name built from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: ttschweizer
    ports:
      - 5001:5001
    volumes:
      - data:/app/data

volumes:
  data: