version: "3.8" 

services:
  app:
    image: ghcr.io/legout/legout/ttschweizer
    container_name: ttschweizer
    ports:
      - 5001:5001
    volumes:
      - data:/app/data
    deploy:
      placement:
        constraints:
          - node.hostname == v2000g11-1.lignobox

volumes:
  data: